/**
 * This class is generated by jOOQ
 */
package org.paggarwal.dockerscheduler.db;


import javax.annotation.Generated;

import org.paggarwal.dockerscheduler.db.tables.EnvironmentVariables;
import org.paggarwal.dockerscheduler.db.tables.Executions;
import org.paggarwal.dockerscheduler.db.tables.QrtzBlobTriggers;
import org.paggarwal.dockerscheduler.db.tables.QrtzCalendars;
import org.paggarwal.dockerscheduler.db.tables.QrtzCronTriggers;
import org.paggarwal.dockerscheduler.db.tables.QrtzFiredTriggers;
import org.paggarwal.dockerscheduler.db.tables.QrtzJobDetails;
import org.paggarwal.dockerscheduler.db.tables.QrtzLocks;
import org.paggarwal.dockerscheduler.db.tables.QrtzPausedTriggerGrps;
import org.paggarwal.dockerscheduler.db.tables.QrtzSchedulerState;
import org.paggarwal.dockerscheduler.db.tables.QrtzSimpleTriggers;
import org.paggarwal.dockerscheduler.db.tables.QrtzSimpropTriggers;
import org.paggarwal.dockerscheduler.db.tables.QrtzTriggers;
import org.paggarwal.dockerscheduler.db.tables.Tasks;
import org.paggarwal.dockerscheduler.db.tables.Users;


/**
 * Convenience access to all tables in dockerscheduler
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dockerscheduler.ENVIRONMENT_VARIABLES
	 */
	public static final EnvironmentVariables ENVIRONMENT_VARIABLES = org.paggarwal.dockerscheduler.db.tables.EnvironmentVariables.ENVIRONMENT_VARIABLES;

	/**
	 * The table dockerscheduler.EXECUTIONS
	 */
	public static final Executions EXECUTIONS = org.paggarwal.dockerscheduler.db.tables.Executions.EXECUTIONS;

	/**
	 * The table dockerscheduler.QRTZ_BLOB_TRIGGERS
	 */
	public static final QrtzBlobTriggers QRTZ_BLOB_TRIGGERS = org.paggarwal.dockerscheduler.db.tables.QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS;

	/**
	 * The table dockerscheduler.QRTZ_CALENDARS
	 */
	public static final QrtzCalendars QRTZ_CALENDARS = org.paggarwal.dockerscheduler.db.tables.QrtzCalendars.QRTZ_CALENDARS;

	/**
	 * The table dockerscheduler.QRTZ_CRON_TRIGGERS
	 */
	public static final QrtzCronTriggers QRTZ_CRON_TRIGGERS = org.paggarwal.dockerscheduler.db.tables.QrtzCronTriggers.QRTZ_CRON_TRIGGERS;

	/**
	 * The table dockerscheduler.QRTZ_FIRED_TRIGGERS
	 */
	public static final QrtzFiredTriggers QRTZ_FIRED_TRIGGERS = org.paggarwal.dockerscheduler.db.tables.QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS;

	/**
	 * The table dockerscheduler.QRTZ_JOB_DETAILS
	 */
	public static final QrtzJobDetails QRTZ_JOB_DETAILS = org.paggarwal.dockerscheduler.db.tables.QrtzJobDetails.QRTZ_JOB_DETAILS;

	/**
	 * The table dockerscheduler.QRTZ_LOCKS
	 */
	public static final QrtzLocks QRTZ_LOCKS = org.paggarwal.dockerscheduler.db.tables.QrtzLocks.QRTZ_LOCKS;

	/**
	 * The table dockerscheduler.QRTZ_PAUSED_TRIGGER_GRPS
	 */
	public static final QrtzPausedTriggerGrps QRTZ_PAUSED_TRIGGER_GRPS = org.paggarwal.dockerscheduler.db.tables.QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS;

	/**
	 * The table dockerscheduler.QRTZ_SCHEDULER_STATE
	 */
	public static final QrtzSchedulerState QRTZ_SCHEDULER_STATE = org.paggarwal.dockerscheduler.db.tables.QrtzSchedulerState.QRTZ_SCHEDULER_STATE;

	/**
	 * The table dockerscheduler.QRTZ_SIMPLE_TRIGGERS
	 */
	public static final QrtzSimpleTriggers QRTZ_SIMPLE_TRIGGERS = org.paggarwal.dockerscheduler.db.tables.QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS;

	/**
	 * The table dockerscheduler.QRTZ_SIMPROP_TRIGGERS
	 */
	public static final QrtzSimpropTriggers QRTZ_SIMPROP_TRIGGERS = org.paggarwal.dockerscheduler.db.tables.QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS;

	/**
	 * The table dockerscheduler.QRTZ_TRIGGERS
	 */
	public static final QrtzTriggers QRTZ_TRIGGERS = org.paggarwal.dockerscheduler.db.tables.QrtzTriggers.QRTZ_TRIGGERS;

	/**
	 * The table dockerscheduler.TASKS
	 */
	public static final Tasks TASKS = org.paggarwal.dockerscheduler.db.tables.Tasks.TASKS;

	/**
	 * The table dockerscheduler.USERS
	 */
	public static final Users USERS = org.paggarwal.dockerscheduler.db.tables.Users.USERS;
}
