/**
 * This class is generated by jOOQ
 */
package org.paggarwal.dockerscheduler.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.paggarwal.dockerscheduler.db.Dockerscheduler;
import org.paggarwal.dockerscheduler.db.Keys;
import org.paggarwal.dockerscheduler.db.tables.records.QrtzTriggersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzTriggers extends TableImpl<QrtzTriggersRecord> {

	private static final long serialVersionUID = -504022754;

	/**
	 * The reference instance of <code>dockerscheduler.QRTZ_TRIGGERS</code>
	 */
	public static final QrtzTriggers QRTZ_TRIGGERS = new QrtzTriggers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<QrtzTriggersRecord> getRecordType() {
		return QrtzTriggersRecord.class;
	}

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.SCHED_NAME</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> SCHED_NAME = createField("SCHED_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.TRIGGER_NAME</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> TRIGGER_NAME = createField("TRIGGER_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.TRIGGER_GROUP</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> TRIGGER_GROUP = createField("TRIGGER_GROUP", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.JOB_NAME</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> JOB_NAME = createField("JOB_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.JOB_GROUP</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> JOB_GROUP = createField("JOB_GROUP", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.DESCRIPTION</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.NEXT_FIRE_TIME</code>.
	 */
	public final TableField<QrtzTriggersRecord, Long> NEXT_FIRE_TIME = createField("NEXT_FIRE_TIME", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.PREV_FIRE_TIME</code>.
	 */
	public final TableField<QrtzTriggersRecord, Long> PREV_FIRE_TIME = createField("PREV_FIRE_TIME", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.PRIORITY</code>.
	 */
	public final TableField<QrtzTriggersRecord, Integer> PRIORITY = createField("PRIORITY", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.TRIGGER_STATE</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> TRIGGER_STATE = createField("TRIGGER_STATE", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.TRIGGER_TYPE</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> TRIGGER_TYPE = createField("TRIGGER_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.START_TIME</code>.
	 */
	public final TableField<QrtzTriggersRecord, Long> START_TIME = createField("START_TIME", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.END_TIME</code>.
	 */
	public final TableField<QrtzTriggersRecord, Long> END_TIME = createField("END_TIME", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.CALENDAR_NAME</code>.
	 */
	public final TableField<QrtzTriggersRecord, String> CALENDAR_NAME = createField("CALENDAR_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.MISFIRE_INSTR</code>.
	 */
	public final TableField<QrtzTriggersRecord, Short> MISFIRE_INSTR = createField("MISFIRE_INSTR", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>dockerscheduler.QRTZ_TRIGGERS.JOB_DATA</code>.
	 */
	public final TableField<QrtzTriggersRecord, byte[]> JOB_DATA = createField("JOB_DATA", org.jooq.impl.SQLDataType.BLOB, this, "");

	/**
	 * Create a <code>dockerscheduler.QRTZ_TRIGGERS</code> table reference
	 */
	public QrtzTriggers() {
		this("QRTZ_TRIGGERS", null);
	}

	/**
	 * Create an aliased <code>dockerscheduler.QRTZ_TRIGGERS</code> table reference
	 */
	public QrtzTriggers(String alias) {
		this(alias, QRTZ_TRIGGERS);
	}

	private QrtzTriggers(String alias, Table<QrtzTriggersRecord> aliased) {
		this(alias, aliased, null);
	}

	private QrtzTriggers(String alias, Table<QrtzTriggersRecord> aliased, Field<?>[] parameters) {
		super(alias, Dockerscheduler.DOCKERSCHEDULER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<QrtzTriggersRecord> getPrimaryKey() {
		return Keys.KEY_QRTZ_TRIGGERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<QrtzTriggersRecord>> getKeys() {
		return Arrays.<UniqueKey<QrtzTriggersRecord>>asList(Keys.KEY_QRTZ_TRIGGERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<QrtzTriggersRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<QrtzTriggersRecord, ?>>asList(Keys.FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzTriggers as(String alias) {
		return new QrtzTriggers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public QrtzTriggers rename(String name) {
		return new QrtzTriggers(name, null);
	}
}
