/**
 * This class is generated by jOOQ
 */
package org.paggarwal.dockerscheduler.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.paggarwal.dockerscheduler.db.Dockerscheduler;
import org.paggarwal.dockerscheduler.db.Keys;
import org.paggarwal.dockerscheduler.db.tables.records.SettingsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings extends TableImpl<SettingsRecord> {

	private static final long serialVersionUID = 1677937745;

	/**
	 * The reference instance of <code>dockerscheduler.SETTINGS</code>
	 */
	public static final Settings SETTINGS = new Settings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SettingsRecord> getRecordType() {
		return SettingsRecord.class;
	}

	/**
	 * The column <code>dockerscheduler.SETTINGS.id</code>.
	 */
	public final TableField<SettingsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.SETTINGS.name</code>.
	 */
	public final TableField<SettingsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>dockerscheduler.SETTINGS.value</code>.
	 */
	public final TableField<SettingsRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * Create a <code>dockerscheduler.SETTINGS</code> table reference
	 */
	public Settings() {
		this("SETTINGS", null);
	}

	/**
	 * Create an aliased <code>dockerscheduler.SETTINGS</code> table reference
	 */
	public Settings(String alias) {
		this(alias, SETTINGS);
	}

	private Settings(String alias, Table<SettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Settings(String alias, Table<SettingsRecord> aliased, Field<?>[] parameters) {
		super(alias, Dockerscheduler.DOCKERSCHEDULER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SettingsRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SETTINGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SettingsRecord> getPrimaryKey() {
		return Keys.KEY_SETTINGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SettingsRecord>> getKeys() {
		return Arrays.<UniqueKey<SettingsRecord>>asList(Keys.KEY_SETTINGS_PRIMARY, Keys.KEY_SETTINGS_UK_SETTINGS_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Settings as(String alias) {
		return new Settings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Settings rename(String name) {
		return new Settings(name, null);
	}
}
