/**
 * This class is generated by jOOQ
 */
package org.paggarwal.dockerscheduler.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.paggarwal.dockerscheduler.db.tables.QrtzBlobTriggers;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzBlobTriggersRecord extends UpdatableRecordImpl<QrtzBlobTriggersRecord> implements Record4<String, String, String, byte[]> {

	private static final long serialVersionUID = 636228449;

	/**
	 * Setter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.SCHED_NAME</code>.
	 */
	public void setSchedName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.SCHED_NAME</code>.
	 */
	public String getSchedName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME</code>.
	 */
	public void setTriggerName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME</code>.
	 */
	public String getTriggerName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP</code>.
	 */
	public void setTriggerGroup(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP</code>.
	 */
	public String getTriggerGroup() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.JOB_DATA</code>.
	 */
	public void setJobData(byte[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_BLOB_TRIGGERS.JOB_DATA</code>.
	 */
	public byte[] getJobData() {
		return (byte[]) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, String, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, byte[]> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, byte[]> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.SCHED_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field4() {
		return QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS.JOB_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getSchedName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTriggerName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTriggerGroup();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getJobData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzBlobTriggersRecord value1(String value) {
		setSchedName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzBlobTriggersRecord value2(String value) {
		setTriggerName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzBlobTriggersRecord value3(String value) {
		setTriggerGroup(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzBlobTriggersRecord value4(byte[] value) {
		setJobData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzBlobTriggersRecord values(String value1, String value2, String value3, byte[] value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QrtzBlobTriggersRecord
	 */
	public QrtzBlobTriggersRecord() {
		super(QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS);
	}

	/**
	 * Create a detached, initialised QrtzBlobTriggersRecord
	 */
	public QrtzBlobTriggersRecord(String schedName, String triggerName, String triggerGroup, byte[] jobData) {
		super(QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS);

		setValue(0, schedName);
		setValue(1, triggerName);
		setValue(2, triggerGroup);
		setValue(3, jobData);
	}
}
