/**
 * This class is generated by jOOQ
 */
package org.paggarwal.dockerscheduler.db.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Record3;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.paggarwal.dockerscheduler.db.tables.QrtzSimpropTriggers;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QrtzSimpropTriggersRecord extends UpdatableRecordImpl<QrtzSimpropTriggersRecord> implements Record14<String, String, String, String, String, String, Integer, Integer, Long, Long, BigDecimal, BigDecimal, Boolean, Boolean> {

	private static final long serialVersionUID = 1070949080;

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.SCHED_NAME</code>.
	 */
	public void setSchedName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.SCHED_NAME</code>.
	 */
	public String getSchedName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME</code>.
	 */
	public void setTriggerName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME</code>.
	 */
	public String getTriggerName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP</code>.
	 */
	public void setTriggerGroup(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP</code>.
	 */
	public String getTriggerGroup() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.STR_PROP_1</code>.
	 */
	public void setStrProp_1(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.STR_PROP_1</code>.
	 */
	public String getStrProp_1() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.STR_PROP_2</code>.
	 */
	public void setStrProp_2(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.STR_PROP_2</code>.
	 */
	public String getStrProp_2() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.STR_PROP_3</code>.
	 */
	public void setStrProp_3(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.STR_PROP_3</code>.
	 */
	public String getStrProp_3() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.INT_PROP_1</code>.
	 */
	public void setIntProp_1(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.INT_PROP_1</code>.
	 */
	public Integer getIntProp_1() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.INT_PROP_2</code>.
	 */
	public void setIntProp_2(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.INT_PROP_2</code>.
	 */
	public Integer getIntProp_2() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_1</code>.
	 */
	public void setLongProp_1(Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_1</code>.
	 */
	public Long getLongProp_1() {
		return (Long) getValue(8);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_2</code>.
	 */
	public void setLongProp_2(Long value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_2</code>.
	 */
	public Long getLongProp_2() {
		return (Long) getValue(9);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_1</code>.
	 */
	public void setDecProp_1(BigDecimal value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_1</code>.
	 */
	public BigDecimal getDecProp_1() {
		return (BigDecimal) getValue(10);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_2</code>.
	 */
	public void setDecProp_2(BigDecimal value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_2</code>.
	 */
	public BigDecimal getDecProp_2() {
		return (BigDecimal) getValue(11);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_1</code>.
	 */
	public void setBoolProp_1(Boolean value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_1</code>.
	 */
	public Boolean getBoolProp_1() {
		return (Boolean) getValue(12);
	}

	/**
	 * Setter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_2</code>.
	 */
	public void setBoolProp_2(Boolean value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>dockerscheduler.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_2</code>.
	 */
	public Boolean getBoolProp_2() {
		return (Boolean) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<String, String, String> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, Integer, Integer, Long, Long, BigDecimal, BigDecimal, Boolean, Boolean> fieldsRow() {
		return (Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, Integer, Integer, Long, Long, BigDecimal, BigDecimal, Boolean, Boolean> valuesRow() {
		return (Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.SCHED_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.STR_PROP_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.STR_PROP_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.STR_PROP_3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.INT_PROP_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.INT_PROP_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field9() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field10() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.LONG_PROP_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field11() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field12() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.DEC_PROP_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field13() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field14() {
		return QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getSchedName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTriggerName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTriggerGroup();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getStrProp_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getStrProp_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getStrProp_3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getIntProp_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getIntProp_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value9() {
		return getLongProp_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value10() {
		return getLongProp_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value11() {
		return getDecProp_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value12() {
		return getDecProp_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value13() {
		return getBoolProp_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value14() {
		return getBoolProp_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value1(String value) {
		setSchedName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value2(String value) {
		setTriggerName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value3(String value) {
		setTriggerGroup(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value4(String value) {
		setStrProp_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value5(String value) {
		setStrProp_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value6(String value) {
		setStrProp_3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value7(Integer value) {
		setIntProp_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value8(Integer value) {
		setIntProp_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value9(Long value) {
		setLongProp_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value10(Long value) {
		setLongProp_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value11(BigDecimal value) {
		setDecProp_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value12(BigDecimal value) {
		setDecProp_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value13(Boolean value) {
		setBoolProp_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord value14(Boolean value) {
		setBoolProp_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QrtzSimpropTriggersRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Integer value8, Long value9, Long value10, BigDecimal value11, BigDecimal value12, Boolean value13, Boolean value14) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QrtzSimpropTriggersRecord
	 */
	public QrtzSimpropTriggersRecord() {
		super(QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS);
	}

	/**
	 * Create a detached, initialised QrtzSimpropTriggersRecord
	 */
	public QrtzSimpropTriggersRecord(String schedName, String triggerName, String triggerGroup, String strProp_1, String strProp_2, String strProp_3, Integer intProp_1, Integer intProp_2, Long longProp_1, Long longProp_2, BigDecimal decProp_1, BigDecimal decProp_2, Boolean boolProp_1, Boolean boolProp_2) {
		super(QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS);

		setValue(0, schedName);
		setValue(1, triggerName);
		setValue(2, triggerGroup);
		setValue(3, strProp_1);
		setValue(4, strProp_2);
		setValue(5, strProp_3);
		setValue(6, intProp_1);
		setValue(7, intProp_2);
		setValue(8, longProp_1);
		setValue(9, longProp_2);
		setValue(10, decProp_1);
		setValue(11, decProp_2);
		setValue(12, boolProp_1);
		setValue(13, boolProp_2);
	}
}
